# Dubbo 注册中心
dubbo:
  registry:
    nacos:
      address: nacos://127.0.0.1:8848


  provider:
    registry:
        protocol: nacos
        port: 8848
        address: ${dubbo.registry.nacos.address}
#    register: false
  consumer:
    registry:
        protocol: nacos
        port: 8848
        address: ${dubbo.registry.nacos.address}

